// Code generated by clients/gen (go run ./clients/gen/main.go). DO NOT EDIT.
//
// interlock.spec.v1 + protocol DTOs. Data types only — no decide, no publish, no
// broker. Enforcement is the trusted Go executable; this package carries shapes
// and (see canonical.ts) the parity-gated canonical encoder, never decisions.

export type Effect = "allow" | "deny";

export type Fidelity = "observed" | "opaque" | "brokered";

export type Operation = "filesystem.read" | "filesystem.write" | "filesystem.delete" | "filesystem.rename_from" | "filesystem.rename_to" | "process.execute" | "artifact.publish" | "vcs.push" | "vcs.force_push";

export type Outcome = "allow" | "deny" | "require" | "fault";

export type RequirementKind = "receipt_status" | "staged_hash_match" | "policy_hash_match" | "target_hash_match" | "human_approval";

export type ResourceKind = "file" | "tree" | "process" | "branch";

export interface SpecDoc {
  protocol: string;
  policy_id: string;
  actors: string[];
  resources: ResourceDoc[];
  rules: RuleDoc[];
}

export interface ResourceDoc {
  id: string;
  kind: ResourceKind;
  uri: string;
}

export interface RuleDoc {
  id: string;
  effect: Effect;
  actor: string;
  operations: Operation[];
  resource: string;
  requires?: Requirement[];
  reason?: string;
}

export interface Policy {
  protocol: string;
  policy_id: string;
  actors: string[];
  resources: Resource[];
  rules: Rule[];
}

export interface Resource {
  id: string;
  kind: ResourceKind;
  uri: string;
}

export interface Rule {
  id: string;
  effect: Effect;
  actor: string;
  operations: Operation[];
  resource: string;
  requires?: Requirement[];
  reason?: string;
}

export interface Requirement {
  kind: RequirementKind;
  receipt?: string;
  status?: string;
  approval?: string;
}

export interface TargetResource {
  kind: ResourceKind;
  uri: string;
}

export interface Observation {
  source: string;
  fidelity: Fidelity;
}

export interface Evidence {
  kind: RequirementKind;
  receipt?: string;
  status?: string;
  value?: string;
}

export interface EffectRequest {
  protocol: string;
  request_id: string;
  run_id: string;
  actor: string;
  operation: Operation;
  resource: TargetResource;
  observation: Observation;
  claimed_policy_hash?: string;
  evidence?: Evidence[];
}

export interface Decision {
  protocol: string;
  request_id: string;
  policy_hash: string;
  outcome: Outcome;
  rule_id?: string;
  reason: string;
  missing_evidence?: Requirement[];
}

export interface Receipt {
  schema: string;
  sequence: number;
  run_id: string;
  request_id: string;
  request_hash: string;
  policy_hash: string;
  rule_id?: string;
  outcome: Outcome;
  evidence_hashes?: string[];
  prev_receipt_hash: string;
  self_hash: string;
}

export interface UpstreamReceipt {
  path: string;
}

export interface PublishRequest {
  run_id: string;
  request_id: string;
  actor: string;
  resource_uri: string;
  kind: ResourceKind;
  staged_path: string;
  target_path: string;
  expected_target_hash?: string;
  upstream?: UpstreamReceipt[];
}
