// Package compat holds Interlock's compatibility-lock corpus: frozen snapshots of
// a released version's policy identity (canonical bytes + hashes), decision
// vectors, broker vectors, and receipt chains. The corpus is embedded and
// re-derived by compat_test.go so that a changed old hash or a changed old
// decision fails CI as a breaking change. New releases may ADD vocabulary and new
// vectors, but a frozen corpus is immutable: it is the contract that today's
// behavior keeps working tomorrow.
//
// The v0.1.0/ tree is generated by conformance/compat/gen (run once, then
// committed). This package only reads it.
package compat

import (
	"bufio"
	"bytes"
	"embed"
	"encoding/json"
	"fmt"

	"github.com/operatorstack/interlock/conformance"
)

//go:embed v0.1.0
var corpus embed.FS

// V010 is the identifier of the first frozen version.
const V010 = "v0.1.0"

// HashRecord freezes one policy's canonical identity: the on-corpus path to its
// canonical bytes and the SHA-256 hash those bytes must produce.
type HashRecord struct {
	Name         string `json:"name"`
	Policy       string `json:"policy"`
	ExpectedHash string `json:"expected_hash"`
}

// EnvelopeSpec is a frozen upstream-evidence envelope description. Bind controls
// how the compat test binds artifact_sha256 to the staged bytes.
type EnvelopeSpec struct {
	Schema string `json:"schema"`
	RunID  string `json:"run_id"`
	Status string `json:"status"`
	Bind   string `json:"bind"` // BindStaged | BindWrong
}

// Envelope binding modes.
const (
	BindStaged = "staged" // artifact_sha256 = hash of the staged bytes
	BindWrong  = "wrong"  // artifact_sha256 = a deliberately wrong hash
)

// BrokerVector freezes one broker outcome: staged content plus an envelope,
// driven through broker.Publish, with the outcome that must not change.
type BrokerVector struct {
	Name        string       `json:"name"`
	Policy      string       `json:"policy"`
	Actor       string       `json:"actor"`
	ResourceURI string       `json:"resource_uri"`
	RunID       string       `json:"run_id"`
	Staged      string       `json:"staged"`
	Env         EnvelopeSpec `json:"env"`
	ExpectOK    bool         `json:"expect_ok"`
}

// ReplayRecord freezes a receipt chain: the policy, the request stream, and the
// receipts, all as on-corpus paths, so replay can be re-run.
type ReplayRecord struct {
	Name     string `json:"name"`
	Policy   string `json:"policy"`
	Requests string `json:"requests"`
	Receipts string `json:"receipts"`
}

// ReadFile returns the raw bytes of a corpus file, given a version-relative path
// (e.g. "policies/exclusive-publish.json").
func ReadFile(version, relpath string) ([]byte, error) {
	return corpus.ReadFile(version + "/" + relpath)
}

// Hashes loads the frozen policy-identity records for a version.
func Hashes(version string) ([]HashRecord, error) {
	var out []HashRecord
	err := readJSONL(version+"/hashes.jsonl", func(b []byte) error {
		var r HashRecord
		if err := json.Unmarshal(b, &r); err != nil {
			return err
		}
		out = append(out, r)
		return nil
	})
	return out, err
}

// Decisions loads the frozen decision vectors for a version. They reuse the
// conformance.Case shape (policy inline, request, expected outcome).
func Decisions(version string) ([]conformance.Case, error) {
	var out []conformance.Case
	err := readJSONL(version+"/decisions.jsonl", func(b []byte) error {
		var c conformance.Case
		if err := json.Unmarshal(b, &c); err != nil {
			return err
		}
		out = append(out, c)
		return nil
	})
	return out, err
}

// BrokerVectors loads the frozen broker vectors for a version.
func BrokerVectors(version string) ([]BrokerVector, error) {
	var out []BrokerVector
	err := readJSONL(version+"/broker.jsonl", func(b []byte) error {
		var v BrokerVector
		if err := json.Unmarshal(b, &v); err != nil {
			return err
		}
		out = append(out, v)
		return nil
	})
	return out, err
}

// ReplayRecords loads the frozen receipt-chain records for a version.
func ReplayRecords(version string) ([]ReplayRecord, error) {
	var out []ReplayRecord
	err := readJSONL(version+"/replay.jsonl", func(b []byte) error {
		var r ReplayRecord
		if err := json.Unmarshal(b, &r); err != nil {
			return err
		}
		out = append(out, r)
		return nil
	})
	return out, err
}

// readJSONL streams the embedded JSONL file at path, invoking fn per non-empty,
// non-comment line.
func readJSONL(path string, fn func([]byte) error) error {
	f, err := corpus.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	line := 0
	for sc.Scan() {
		line++
		b := bytes.TrimSpace(sc.Bytes())
		if len(b) == 0 || b[0] == '#' {
			continue
		}
		if err := fn(b); err != nil {
			return fmt.Errorf("%s:%d: %w", path, line, err)
		}
	}
	return sc.Err()
}
