# Code generated by clients/gen (go run ./clients/gen/main.go). DO NOT EDIT.
#
# interlock.spec.v1 + protocol DTOs. Data types only — no decide, no publish, no
# broker. Enforcement is the trusted Go executable; this package carries shapes
# and (see canonical.py) the parity-gated canonical encoder, never decisions.
from __future__ import annotations

from typing import Literal, Required, TypedDict

Effect = Literal["allow", "deny"]
Fidelity = Literal["observed", "opaque", "brokered"]
Operation = Literal["filesystem.read", "filesystem.write", "filesystem.delete", "filesystem.rename_from", "filesystem.rename_to", "process.execute", "artifact.publish", "vcs.push", "vcs.force_push"]
Outcome = Literal["allow", "deny", "require", "fault"]
RequirementKind = Literal["receipt_status", "staged_hash_match", "policy_hash_match", "target_hash_match", "human_approval"]
ResourceKind = Literal["file", "tree", "process", "branch"]

class SpecDoc(TypedDict, total=False):
    protocol: Required[str]
    policy_id: Required[str]
    actors: Required[list[str]]
    resources: Required[list[ResourceDoc]]
    rules: Required[list[RuleDoc]]


class ResourceDoc(TypedDict, total=False):
    id: Required[str]
    kind: Required["ResourceKind"]
    uri: Required[str]


class RuleDoc(TypedDict, total=False):
    id: Required[str]
    effect: Required["Effect"]
    actor: Required[str]
    operations: Required[list[Operation]]
    resource: Required[str]
    requires: list[Requirement]
    reason: str


class Policy(TypedDict, total=False):
    protocol: Required[str]
    policy_id: Required[str]
    actors: Required[list[str]]
    resources: Required[list[Resource]]
    rules: Required[list[Rule]]


class Resource(TypedDict, total=False):
    id: Required[str]
    kind: Required["ResourceKind"]
    uri: Required[str]


class Rule(TypedDict, total=False):
    id: Required[str]
    effect: Required["Effect"]
    actor: Required[str]
    operations: Required[list[Operation]]
    resource: Required[str]
    requires: list[Requirement]
    reason: str


class Requirement(TypedDict, total=False):
    kind: Required["RequirementKind"]
    receipt: str
    status: str
    approval: str


class TargetResource(TypedDict, total=False):
    kind: Required["ResourceKind"]
    uri: Required[str]


class Observation(TypedDict, total=False):
    source: Required[str]
    fidelity: Required["Fidelity"]


class Evidence(TypedDict, total=False):
    kind: Required["RequirementKind"]
    receipt: str
    status: str
    value: str


class EffectRequest(TypedDict, total=False):
    protocol: Required[str]
    request_id: Required[str]
    run_id: Required[str]
    actor: Required[str]
    operation: Required["Operation"]
    resource: Required["TargetResource"]
    observation: Required["Observation"]
    claimed_policy_hash: str
    evidence: list[Evidence]


class Decision(TypedDict, total=False):
    protocol: Required[str]
    request_id: Required[str]
    policy_hash: Required[str]
    outcome: Required["Outcome"]
    rule_id: str
    reason: Required[str]
    missing_evidence: list[Requirement]


class Receipt(TypedDict, total=False):
    schema: Required[str]
    sequence: Required[int]
    run_id: Required[str]
    request_id: Required[str]
    request_hash: Required[str]
    policy_hash: Required[str]
    rule_id: str
    outcome: Required["Outcome"]
    evidence_hashes: list[str]
    prev_receipt_hash: Required[str]
    self_hash: Required[str]


class UpstreamReceipt(TypedDict, total=False):
    path: Required[str]


class PublishRequest(TypedDict, total=False):
    run_id: Required[str]
    request_id: Required[str]
    actor: Required[str]
    resource_uri: Required[str]
    kind: Required["ResourceKind"]
    staged_path: Required[str]
    target_path: Required[str]
    expected_target_hash: str
    upstream: list[UpstreamReceipt]
